- name: Install sshfs
  apt:
        name: sshfs
        state: present

- name: Create a directory where to mount sshfs
  ansible.builtin.file:
    path: "{{ ssh_fs_mount_directory }}"
    state: directory
    mode: '0755'

- name: create directory /root/.ssh
  file:
    path: /root/.ssh
    state: directory
    mode: '0700'
    owner: 'root'
    group: 'root'
    
- name: Generate an OpenSSH keypair
  community.crypto.openssh_keypair:
    path: /root/.ssh/sshfs
    
- name: Add fstab
  lineinfile:
    path: /etc/fstab
    line: "{{ ssh_fs_mount_connection }} {{ ssh_fs_mount_directory }} fuse.sshfs x-systemd.automount,_netdev,reconnect,identityfile=/root/.ssh/sshfs,allow_other,default_permissions 0 0"
