- name: Create a directory /etc/apt/keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'


- name: Add gpg for docker
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args: 
      creates: /etc/apt/keyrings/docker.gpg

- name: Add repo for docker
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list 
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Install Docker CE
  apt:
    pkg:
      - bash-completion
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
    update_cache: true

    
- name: Download docker bash auto complete
  get_url:
       url: https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker
       dest: "/etc/bash_completion.d/docker"
       mode: 0644
       group: "root"
       owner: "root"

